package demo;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;
import static org.junit.Assert.*;


public class VehicleTest {
@Test public void testSomeVehicleMethod() {
	VehicleTest classUnderTest = new VehicleTest();
}
}
